### ISSUE TITLE
Model presets DOES change the outcome.

### ISSUE THREAD

**Issue by sokrypton** [porterll/CF-random#1]
See additional analysis for FigS1a:
https://twitter.com/sokrypton/status/1752179213929435504

**Comment by mlsbio** [comment]
This issue should be reopened. The page still says "Model presets do not change our conclusions"

Please fix ASAP.

**Comment by sokrypton** [comment]
This issue should be reopened. The page still says "Model presets do not change our conclusions"

Please fix ASAP.

**Comment by porterll** [comment]
This is still my opinion.  The reviewers did not ask me to revise it.

**Comment by sokrypton** [comment]
It's not a matter of opinion. It DOES change your conclusion. Your conclusion "We were surprised by the Paper’s claim ... we had not seen AF2 generate correct models of the autoinhibited state from full MSAs with plDDTs so low" is WRONG.

Reviewers cannot catch everything wrong. Just cus you snuck something past the reviewers doesn't justify it.
